engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
    checks:
      UnusedLocalVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/